#!/bin/bash
export LDFLAGS=""
export CPPFLAGS=""
export CXXFLAGS="\
-march=prescott \
-O3 \
-pipe \
-fomit-frame-pointer \
-ffast-math \
"
export USER_CONFIG_OPTS="--disable-cxx-flags-preset"

# Option -ftree-vectorize is disabled. It's apparently not a safe flag
# to use. See:
# http://actin.ucd.ie/trac/genepi/wiki/Autovectorization%20in%20GCC
#
# -ftree-vectorize -ftree-vectorizer-verbose=3

source "$(pwd)/src/scripts/build-common"
