#!/bin/bash
export LDFLAGS=""
export CPPFLAGS=""
export CXXFLAGS="-march=k8 -O3 -pipe -fomit-frame-pointer \
-ffast-math \
-ftree-vectorize -ftree-vectorizer-verbose=3"

source "$(pwd)/src/scripts/build-common"
