#!/bin/bash
export LDFLAGS=""
export CPPFLAGS=""
# -ffast-math was removed because of problem with the score test
# http://actin.ucd.ie/trac/genepi/ticket/52
export CXXFLAGS="\
-march=k8 \
-O3 \
-pipe \
-fomit-frame-pointer \
"

# Option -ftree-vectorize is disabled. It's apparently not a safe flag
# to use. See:
# http://actin.ucd.ie/trac/genepi/wiki/Autovectorization%20in%20GCC
#
# -ftree-vectorize -ftree-vectorizer-verbose=3

USER_CONFIG_OPTS="--disable-cxx-flags-preset"
source "$(pwd)/src/scripts/build-common"
