#!/bin/bash
export LDFLAGS=""
export CPPFLAGS=""
export CXXFLAGS=""
export EXTRAFLAGS="-march=i686"
# export CXXFLAGS="-g -O0 -march=i686 -Wall"
# USER_CONFIG_OPTS="--enable-testing"
export USER_CONFIG_OPTS="--enable-debug"

source "$(pwd)/src/scripts/build-common"
