#!/bin/bash
export LDFLAGS=""
export CPPFLAGS=""
# export CXXFLAGS="-g -O0 -march=i686 -Wall -Werror"
export CXXFLAGS="-g -O0 -march=i686 -Wall"
USER_CONFIG_OPTS="--enable-testing"

source "$(pwd)/src/scripts/build-common"
