#!/bin/bash

# This is for profiling on Core 2 Duo (architecture nocona)
export LDFLAGS=""
export CPPFLAGS=""
export EXTRA_FLAGS="\
-march=nocona \
-O3 \
-ffast-math \
"

# Option -ftree-vectorize is disabled. It's apparently not a safe flag
# to use. See:
# http://actin.ucd.ie/trac/genepi/wiki/Autovectorization%20in%20GCC
#
# -ftree-vectorize -ftree-vectorizer-verbose=3

USER_CONFIG_OPTS="--enable-profile"
source "$(pwd)/src/scripts/build-common"
