#!/bin/bash
# 
# Source:
# http://actin.ucd.ie/trac/genepi/wiki/Building%20hapmixmap%20on%20ICHEC
#

. ${MODULESHOME}/init/sh
module unload pathscale
module unload mpich/path
module unload mpich/gcc
module load gcc4
module load mpich/gcc4
export CC="mpicc"
export CXX="mpiCC"
export LDFLAGS="-L/opt/packages/sprng-2.0/lib"
export CPPFLAGS="-I/opt/packages/sprng-2.0/include"
# gcc-4 has architecture `opteron' (gcc-3 hasn't)
export CXXFLAGS="\
-march=opteron \
-O3 \
-fomit-frame-pointer \
-pipe \
-ffast-math \
"

# Option -ftree-vectorize is disabled. It's apparently not a safe flag
# to use. See:
# http://actin.ucd.ie/trac/genepi/wiki/Autovectorization%20in%20GCC
#
# -ftree-vectorize -ftree-vectorizer-verbose=3

USER_CONFIG_OPTS="--enable-parallel"

source "$(pwd)/src/scripts/build-common"
