#!/bin/bash

# This is for profiling on Core 2 Duo (architecture nocona)
export LDFLAGS=""
export CPPFLAGS=""
export CXXFLAGS="\
-march=nocona \
-O3 \
-ffast-math \
-ftree-vectorize -ftree-vectorizer-verbose=3 \
-pg \
"

source "$(pwd)/src/scripts/build-common"
