#!/bin/bash

# if [ "$0" != "-bash" ]
# then
# 	echo "Please use the 'source' command to execute this script."
# 	exit 1
# fi

if [ -w /usr/bin ]
then
	USER_PREFIX="/usr"
else
	USER_PREFIX="$HOME/usr"
fi

# Check the PATH

if [ "$USER_PREFIX" = "$HOME/usr" -a -z "$(echo $PATH | grep "$HOME/usr")" ]
then
	echo
	echo "Your \$PATH not set to $HOME/usr/bin."
	export PATH="$HOME/usr/bin:$PATH"
	echo "Setting your PATH to $PATH"
	echo
fi

if [ ! -x "./configure" ]
then
	echo "./configure not present, bootstrapping"
	./bootstrap
else
	echo "./configure present, invoking autoreconf"
	autoreconf
fi

make distclean

echo "CXXFLAGS='$CXXFLAGS'"
echo "CPPFLAGS='$CPPFLAGS'"
echo "LDFLAGS='$LDFLAGS'"
echo
echo ./configure --prefix "${USER_PREFIX}" ${USER_CONFIG_OPTS}
./configure --prefix "${USER_PREFIX}" ${USER_CONFIG_OPTS}
if [ "$?" != "0" ]
then
	echo "Configure failed."
	exit 1
fi
make clean
make -j3 && make install
if [ "$?" = "0" ]
then
	echo
	echo "Build successful."
	echo "You your binary should be now installed in ${USER_PREFIX}/bin."
	echo
	ls -l "${USER_PREFIX}/bin"
	echo
else
	echo
	echo "Build failed."
	echo
fi
