#!/bin/bash
# -*- coding: UTF-8 -*-
#
# Perform an operation on all the directories in the configuration file
#
# Copyright (C) 2007 Maciej Bliziński
# 
# This script is free software distributed WITHOUT ANY WARRANTY. 
# You can redistribute it and/or modify it under the terms of the
# GNU General Public License, 
# version 2 or later, as published by the Free Software Foundation. 
# See the file COPYING for details.
# 
 
function usage() {
echo "Usage: $0 <config> <command> [ <options> ]"
exit "$1"
}

if [[ -z "$1" || -z "$2" ]]; then usage 1; fi

ANALYSES_CONF="$1"
shift

while read LINE
do
	# Skip comments
	if [[ "$(echo ${LINE} | head -c 1)" = "#" ]]; then continue; fi
	ANALYSIS_DIR="$(echo ${LINE} | cut -d: -f1)"
	pushd "../${ANALYSIS_DIR}" > /dev/null
	# echo -- "$@"
	"$@"
	popd > /dev/null
done < "${ANALYSES_CONF}"
