/*         DO NOT EDIT THIS FILE!!        */
/* -- AUTOGENERATED FROM *_source FILE -- */
// matrix_i.h
#ifndef MATRIX_MATRIX_i_H
#define MATRIX_MATRIX_i_H 1

#include <iostream>
#include <iomanip>
#include <cassert>

#include <gsl/gsl_math.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_linalg.h>
#include <gsl/gsl_blas_types.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_ieee_utils.h>
#include <gsl/gsl_eigen.h>

#include <vector>

class Vector;
class Vector_d;
class Vector_i;

class Matrix;
class Matrix_d;
class Matrix_i;

class Matrix_i
{
 private: // members
  std::vector<size_t> _MissingCol;
  std::vector<size_t> _MissingRow;
  gsl_matrix_int * _matrix;
  
  // GLOBAL FRIENDS
  friend Matrix_i
    ConcatenateHorizontally( const Matrix_i& m1, const Matrix_i& m2 );

  friend std::ostream&
    operator<< ( std::ostream& os, const Matrix_i& M );

  friend void
    operator>> ( const char * FileName, Matrix_i& M );

  friend Matrix_i
    operator*( int, const Matrix_i& m);

 public:
  // CONSTRUCTORS
  // default constructor
  Matrix_i();

  // copy constructor
  Matrix_i(const Matrix_i& M);

  // number of rows and columns
  Matrix_i(size_t NewRows, size_t NewCols);


  // DESTRUCTOR
  ~Matrix_i();


  // ASSIGNMENT OPERATORS
  Matrix_i&
    operator=(const Matrix& m);

  Matrix_i&
    operator=(const Matrix_d& m);

  Matrix_i&
    operator=(const Matrix_i& m);

  
  // CONVERTERS
  Matrix_d
    Double() const;

  Matrix
    Float() const;

  Matrix_i
    Integer() const;


  // OPERATORS
  int&
     operator()(int row, int col);

  int&
     operator()(int row, int col) const;

  Matrix_i
    operator+(int f) const;

  Matrix_i
    &operator*=(const int f);

  Matrix_i
    operator+(const Matrix& m) const;

  Matrix_i
    operator+(const Matrix_i& m) const;

  Matrix_i
    operator+(const Matrix_d& m) const;

  Matrix_i&
    operator+=(const Matrix_i& m);

  Matrix_i
    operator-(const Matrix_i& m) const;

  Matrix_i
    operator*(int f) const;

  Matrix_i
    operator*(const Matrix_i& m) const;

  Matrix_i
    operator/(int) const;

  Matrix_i&
    operator/=(int);

  // ACCESSORS
  
  Vector_i
    GetColumn(int col) const;

  void
    SetColumn(int col, const Vector_i& v);

  Vector_i
    GetDiagonal() const;

  void
    SetDiagonal(int);
  
  void
    SetElements(int NewValue);

  void
    SetMissingElement(int row, int col);

  bool
    IsMissingValue(int row, int col) const;

  int
    GetMissingValueCol(int index) const;

  int
    GetMissingValueRow(int index) const;

  int
    GetNumberOfCols() const;

  int
    GetNumberOfRows() const;

  void
    SetNumberOfElements(size_t NewRows, size_t NewCols);

  int
    GetNumberOfMissingValues() const;

  Vector_i
    GetRow(int row) const;

  void
    SetRow(int row, const Vector_i& v);


  
  // FILE ACCESS
  void
    Load( const char *FileName );



  // OBJECT METHODS
  int
    CholeskyDecomposition(Matrix_i*) const;

  Vector_i
    ColumnMean() const;

  double
    Determinant() const;

  void
    Eigenvalue2(Vector_i*);

  Matrix_i
    FindElement( int );
  
  void
    InvertUsingLUDecomposition();

  double
    LogDeterminant( int *sign ) const;

  Vector_i
    RowMean() const;

  Vector_i
    RowSum() const;

  void
    SetMissingValuesToColumnMeans();

  Matrix_i
    SubMatrix( int rowstart, int rowfinish,
	       int colstart, int colfinish) const;   
  
  void
    SubMatrix2(int rowstart, int rowfinish,
	       int colstart, int colfinish);   
  
  void
    Symmetrize();
  
  Matrix_i
    Transpose() const;
  
  bool
    IsSymmetric() const;

 private:

  // PRIVATE HELPER METHODS
  Vector_i
    ColumnSum() const;

  Vector_i
    ColumnMeanExcludingMissingValues() const;

  Vector_i
    ColumnSumExcludingMissingValues() const;

  double
    LU_lndet();

  int
    LU_decomp (gsl_permutation * p);
};

#endif /* !defined MATRIX_MATRIXint_H */
