/*         DO NOT EDIT THIS FILE!!        */
/* -- AUTOGENERATED FROM *_source FILE -- */
// matrix.h
#ifndef MATRIX_MATRIX_H
#define MATRIX_MATRIX_H 1

#include <iostream>
#include <iomanip>
#include <cassert>

#include <gsl/gsl_math.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_linalg.h>
#include <gsl/gsl_blas_types.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_ieee_utils.h>
#include <gsl/gsl_eigen.h>

#include <vector>

class Vector;
class Vector_d;
class Vector_i;

class Matrix;
class Matrix_d;
class Matrix_i;

class Matrix
{
 private: // members
  std::vector<size_t> _MissingCol;
  std::vector<size_t> _MissingRow;
  gsl_matrix_float * _matrix;
  
  // GLOBAL FRIENDS
  friend Matrix
    ConcatenateHorizontally( const Matrix& m1, const Matrix& m2 );

  friend std::ostream&
    operator<< ( std::ostream& os, const Matrix& M );

  friend void
    operator>> ( const char * FileName, Matrix& M );

  friend Matrix
    operator*( float, const Matrix& m);

 public:
  // CONSTRUCTORS
  // default constructor
  Matrix();

  // copy constructor
  Matrix(const Matrix& M);

  // number of rows and columns
  Matrix(size_t NewRows, size_t NewCols);


  // DESTRUCTOR
  ~Matrix();


  // ASSIGNMENT OPERATORS
  Matrix&
    operator=(const Matrix& m);

  Matrix&
    operator=(const Matrix_d& m);

  Matrix&
    operator=(const Matrix_i& m);

  
  // CONVERTERS
  Matrix_d
    Double() const;

  Matrix
    Float() const;

  Matrix_i
    Integer() const;


  // OPERATORS
  float&
     operator()(int row, int col);

  float&
     operator()(int row, int col) const;

  Matrix
    operator+(float f) const;

  Matrix
    &operator*=(const float f);

  Matrix
    operator+(const Matrix& m) const;

  Matrix
    operator+(const Matrix_i& m) const;

  Matrix
    operator+(const Matrix_d& m) const;

  Matrix&
    operator+=(const Matrix& m);

  Matrix
    operator-(const Matrix& m) const;

  Matrix
    operator*(float f) const;

  Matrix
    operator*(const Matrix& m) const;

  Matrix
    operator/(float) const;

  Matrix&
    operator/=(float);

  // ACCESSORS
  
  Vector
    GetColumn(int col) const;

  void
    SetColumn(int col, const Vector& v);

  Vector
    GetDiagonal() const;

  void
    SetDiagonal(float);
  
  void
    SetElements(float NewValue);

  void
    SetMissingElement(int row, int col);

  bool
    IsMissingValue(int row, int col) const;

  int
    GetMissingValueCol(int index) const;

  int
    GetMissingValueRow(int index) const;

  int
    GetNumberOfCols() const;

  int
    GetNumberOfRows() const;

  void
    SetNumberOfElements(size_t NewRows, size_t NewCols);

  int
    GetNumberOfMissingValues() const;

  Vector
    GetRow(int row) const;

  void
    SetRow(int row, const Vector& v);


  
  // FILE ACCESS
  void
    Load( const char *FileName );



  // OBJECT METHODS
  int
    CholeskyDecomposition(Matrix*) const;

  Vector
    ColumnMean() const;

  double
    Determinant() const;

  void
    Eigenvalue2(Vector*);

  Matrix
    FindElement( float );
  
  void
    InvertUsingLUDecomposition();

  double
    LogDeterminant( int *sign ) const;

  Vector
    RowMean() const;

  Vector
    RowSum() const;

  void
    SetMissingValuesToColumnMeans();

  Matrix
    SubMatrix( int rowstart, int rowfinish,
	       int colstart, int colfinish) const;   
  
  void
    SubMatrix2(int rowstart, int rowfinish,
	       int colstart, int colfinish);   
  
  void
    Symmetrize();
  
  Matrix
    Transpose() const;
  
  bool
    IsSymmetric() const;

 private:

  // PRIVATE HELPER METHODS
  Vector
    ColumnSum() const;

  Vector
    ColumnMeanExcludingMissingValues() const;

  Vector
    ColumnSumExcludingMissingValues() const;

  double
    LU_lndet();

  int
    LU_decomp (gsl_permutation * p);
};

#endif /* !defined MATRIX_MATRIXfloat_H */
