#!/bin/bash

WORKING_DIR="legend"
OUT_FILE="rs_data.csv"

rm -f "$OUT_FILE"

if [ ! -d "$WORKING_DIR" ]
then
	echo "Can't open '$WORKING_DIR' directory."
	exit 1
fi

for CHROMOSOME in $(seq 1 22)
do
	FILES="$WORKING_DIR/genotypes_chr${CHROMOSOME}_*.txt.gz"
	# echo $FILES
	for FILE in $FILES
	do
		echo -n "."
		CHROMOSOME=$(echo -n $FILE | cut -d_ -f2)
		zcat "$FILE" \
			| grep -v "position" \
			| sed -e "s/.*/&\t$CHROMOSOME/" \
			>> "$OUT_FILE"
		echo >> "$OUT_FILE"
	done
done
echo

echo "Sorting and removing duplicates; it can take few minutes."
time \
cat "$OUT_FILE" \
	| grep -v -E '^$' \
	| sort | uniq \
	> tmp
mv tmp "$OUT_FILE"
